### ISSUE TITLE
Bopomofo graphs looks bad, unlike others. and…

### ISSUE THREAD

**Issue by MY1L** [unicode-org/cjk-symbols#3] opened 2023-11-25 03:57 UTC
Being poor at English）检查的文件：CJKSymbols-Regular.otf 2.000

## Bopomofo

比较形似的ム和ㄊ：
![image](https://github.com/unicode-org/cjk-symbols/assets/58043328/0c8735cc-42e9-471d-b075-6a8552f2f5da)
甚至是折线？
![image](https://github.com/unicode-org/cjk-symbols/assets/58043328/14330031-11c7-4641-831e-a4d1826728c7)

## 〜

〾也是：
![image](https://github.com/unicode-org/cjk-symbols/assets/58043328/0742166f-c3c4-46c9-8132-0182d1c7de84)

我索性重画了一个给你（文件见下）
![image](https://github.com/unicode-org/cjk-symbols/assets/58043328/9dbc1a65-4565-4287-b988-ecb665360bb8)

## Suzhou Numerals

苏州码子〸〹〺字体不一致：
![image](https://github.com/unicode-org/cjk-symbols/assets/58043328/09ac17d8-392d-4a2e-913e-30d3ba4c693d)

我改为一致，还修改了了其它几个字（文件见下，〥取自我2021年做的[源意明体](https://github.com/MY1L/HanItalic/releases/tag/SrcMing)）
![image](https://github.com/unicode-org/cjk-symbols/assets/58043328/7040005a-1875-4648-8891-f3cd404e9589)
（with all due respect, [SourceHanSerif](https://twitter.com/MY1Ltype/status/1728288237851132144)’s 〥 & Bopomofo look so ugly.）
![image](https://github.com/unicode-org/cjk-symbols/assets/58043328/3bed17ec-67f3-4154-b987-e9df1a0333c1)

字形依据：
### 〦二〥〩
位于长城附近永久保存的青龙桥车站的里程碑视频（[央视九台纪录片频道《创新中国》第6集](https://www.bilibili.com/video/av18818462) 6分25秒左右，于[2018-01-28](https://www.zhihu.com/question/19633798/answer/305401974)截屏）：
![$R](https://github.com/unicode-org/cjk-symbols/assets/58043328/e6871cd2-5a25-4bd3-a41b-3f19e2f3a122)
![$R1U3S](https://github.com/unicode-org/cjk-symbols/assets/58043328/ef056099-d913-48ea-a907-48fcff7228d2)

> 致谢 **钛白**(@TaicEart)
他经过考据认为微软雅黑〦〧〨〩等字写法有误，且〡〢〣相遇时应变换方向。得知微软雅黑将更替字形时，在2016年11月就（于 Renzhi Li @be5invis 的微信群）提供了苏州码子无级字重黑体“[TiSu](https://github.com/TaicEart/TiSu)”用于更替字形，并想对ISO\统一码提案。但更替微软雅黑计划中断，均不了了之，于是在2017年10月26日将 TiSu 免费发布。
![TiSu-600](https://github.com/unicode-org/cjk-symbols/assets/58043328/92aa06a3-fb53-4a93-ba18-930f5ecd11ca)
（图为 TiSu-SemiBold，其中〩为草书形式，支持〡〢〣相遇时变换方向的特性）
我与 @NightFurySL2001 [关于〩的提案](https://www.unicode.org/L2/L2023/23231.htm#177-C12)受到 TaicEart 启发。

### 〡〢〣〤〥〦〧〨
![思源宋的〥](https://github.com/unicode-org/cjk-symbols/assets/58043328/439cdd9c-b338-4b2b-9804-56b172a3f57d)

## Symbols for Chinese folk religion

🉠🉡🉢🉣🉤🉥也有类似的问题，直线上不应该有锚点，显得弯弯曲曲的：
![image](https://github.com/unicode-org/cjk-symbols/assets/58043328/2a1c00f3-fe9d-485e-9842-307c685736da)

恰好这个问题可以解决，[我几年前](https://space.bilibili.com/273931293)就画了🉤这些字形，

![image](https://github.com/unicode-org/cjk-symbols/assets/58043328/8b13ac18-41f6-4029-8219-2ba6c4abe58d)![image](https://github.com/unicode-org/cjk-symbols/assets/58043328/0436b3cd-77a4-4109-a1a5-b78509c75333)

3次曲线，OFL1.1的，目前有新版：https://github.com/MY1L/Unicode/releases/tag/Hani9

## Font

除了Bopomofo，以上所有修改（〡〢〣〤〥〦〧〨〩〸〹〺〾🉠🉡🉢🉣🉤🉥）打包为笔画分离的otf：[CJKSymbols.patch.zip](https://github.com/unicode-org/cjk-symbols/files/13462961/CJKSymbols2.001.zip)

**Comment by kenlunde** [comment] 2023-12-06 14:21
Thank you. Because representative glyph changes are involved for some of characters, this issue will be discussed during the UTC #178 meeting in January as document [L2/23-281](https://www.unicode.org/cgi-bin/GetDocumentLink?L2/23-281). I will let you know of the outcome after the meeting.

**Comment by NightFurySL2001** [comment] 2024-01-11 23:10
Please sign this CLA to allow the Unicode consortium to use your updated glyph data.

请签署下面的贡献者许可协议，同意 Unicode联盟使用您的更新数据。
 https://cla-assistant.io/unicode-org/.github

**Comment by kenlunde** [comment] 2024-01-14 19:47
@MY1L Please respond to the request above.

**Comment by MY1L** [comment] 2024-01-16 01:00
（几天前已经签过忘记回复了 / a few days ago I signed the CLA）

有件尴尬的事，我才想起我已经在2021年就相关议题在思源宋那边 @kenlunde 过：[Suzhou numerals glyphs are still not redesigned; and 々,乄 needs to be redesigned in CN Subset, etc. adobe-fonts/source-han-serif#131](https://github.com/adobe-fonts/source-han-serif/issues/131) 
(由于我正在修改思源宋源文件，就不在这边提了 / a issue merely about SourceHanSerif, not here.)

**Comment by kenlunde** [comment] 2024-01-16 01:09
@MY1L Thank you for signing the CLA. I have asked one of the administrators to confirm.

About the Source Han / Noto CJK repositories, I have not been involved in them for approximately 4.5 years ago.

**Comment by kenlunde** [comment] 2024-01-16 03:48
One of the administrators confirmed that you signed the CLA. 谢谢!

**Comment by MY1L** [comment] 2024-01-20 03:03
Can I add/revise some glyphs? 
⿼⿽(￫)⿾⿿㇯〢〤〥〦〧〨〩〸〹〺々(change from SourceHanSerifVF, arrows are also variable)
![￫](https://github.com/unicode-org/cjk-symbols/assets/58043328/f5f359a8-9d72-4449-be14-e3cc7345c5d0)

**Comment by kenlunde** [comment] 2024-01-20 13:40
This is not a variable font, so I do not see any benefit in such changes.

**Comment by MY1L** [comment] 2024-01-23 14:45
updated, sample text: ⿼⿽⿾⿿㇯㇒㇣〢〤〦〥〧〨〩〸〹〺々(𠚤)
![image](https://github.com/unicode-org/cjk-symbols/assets/58043328/ece15cf4-1ef9-4c27-9368-a285168c3e1c)

[CJKSymbolsPatch2.zip](https://github.com/unicode-org/cjk-symbols/files/14025378/CJKSymbolsPatch2.zip)
> CJKSymbolsPatch2glyphs-SrcHanSe-Regular.otf — intended to Source
> CJKSymbolsPatch2.ttf — intended to PDF

**Comment by kenlunde** [comment] 2024-01-24 12:38
I can incorporate all of these minor glyph tweaks except for that of `U+3005 々 IDEOGRAPHIC ITERATION MARK` whose proposed glyph change deviates too much from common usage.

**Comment by kenlunde** [comment] 2024-01-25 05:03
Closing per Version 2.001 release.

**Closed as completed by kenlunde** 2024-01-25 05:03 UTC

**Comment by MY1L** [comment] 2024-03-17 12:31
i see https://github.com/unicode-org/cjk-symbols/commit/9c0aa17ebfc2fd53f5f610b01e1b9e440b898954
`table name {  nameid 0`

@kenlunde may i ask if it is possible to include my id in the list of contributors(nameid 0)?

**Comment by kenlunde** [comment] 2024-03-17 12:39
I already thought about that, but including something like `MY1L` is a bit cryptic. This is the reason why it was not done. We prefer something that resembles the name of an actual person. Still, such a change, which is to the metadata, is not a reason to bump the version number and to make a new release, but if you can provide something that resembles the name of an actual person, I can make sure that it is included in the next version.

**Comment by MY1L** [comment] 2024-03-17 13:39
I understand, but `MYIL` is indeed my vendor ID — there are may thousands of people with the duplication name as me (pinyin, without tone), so can't even find myself online by name…

how about ~“Yi Hu 'MY1L'”~(sounds not well in Chinese) or “HU 'MY1L' Yi” or “'MY1L' Hu”?

**Comment by kenlunde** [comment] 2024-03-17 14:20
How about putting `MY1L` in parentheses? In case `Yi Hu (MY1L)`, which would follow the pattern of other names in the same `name.id=0` string, does not sound well, I would suggest `HU Yi (MY1L)` instead.

**Comment by MY1L** [comment] 2024-03-18 14:08
Okay..（btw, “MY1L” already includes my personalname(1=一→Yi≈Y1,wordplay😓), so, can be deduplication as “MY1L Hu”）

Oh, one more question —
![image](https://github.com/unicode-org/cjk-symbols/assets/58043328/41dc2eea-9ce7-40d2-9dd3-78e098905307)
https://www.unicode.org/charts/PDF/Unicode-16.0/U160-3000.pdf
https://www.unicode.org/charts/PDF/Unicode-16.0/U160-31C0.pdf

**Comment by kenlunde** [comment] 2024-03-19 04:23
So, which attribution do you prefer?

Also, while the _CJK Symbols_ font was developed to be used for the code charts of the Unicode Standard, the code charts editor ultimately decides for which code points to use the _CJK Symbols_ font. This is why you observed what you did in the Unicode Version 16.0 Alpha code charts.

**Comment by MY1L** [comment] 2024-03-20 08:22
`MY1L Hu` may be better (if allowed)

**Comment by kenlunde** [comment] 2024-03-24 17:17
This will work. I will append `MY1L Hu` to the `name.ID=0` string the next time the font is updated.
